### ISSUE TITLE
probably bug

### ISSUE THREAD

**Issue by chcnetconsulting** [cbrunet/typo3-cb_newscal#11]
Although I have in my news for a special day 2 news elements, only the first is shown. All settings seem to be proper....

**Comment by chcnetconsulting** [comment]
yep - bug :) 

Controller/NewsController.php row 140: unset($this->events[$day['year']][$day['month']][$k]);*\* in getEventsOfDay kills all other events of that day, so that we have only the first displayed.

Because we are processing one event after the other, it's not necessary to explicitly kill the event, we have added. That kills the foreach conditions....
- Christoph

**Comment by cbrunet** [comment]
Normally, I should be able to delete the items as I use them. But it seems what I get from news is not a simple array, but a kind of iterator. I removed the unsets, but it means it will loops through all events of the month, for each day. Thank you for reporting this.

**Comment by chcnetconsulting** [comment]
you're welcome :)

Why don't you convert that object to an array? Then you can unset already checked events. btw. I have tested also the newsevent implementation, a few lines above in the same script... There was also a bug, but I didn't investigate that further....
