### ISSUE TITLE
2 Events on the same day

### ISSUE THREAD

**Issue by CarstenHager** [cbrunet/typo3-cb_newscal#6]
It is not possible to display 2 Events on the same day

**Comment by cbrunet** [comment]
Why are you saying that? The default provided template should display the list of events, for a given day, as a popup. 

If you need a different behavior, it is possible to modify the template to display it the way you want. 

Please provide more details about the problem you describe.

**Comment by CarstenHager** [comment]
http://p226109.mittwaldserver.info/dein-stadtteil/duerrbachtal/

2 Events on 21.01.15 - see the List Views
But only 1 Event in the calender View
I use the default template.

**Comment by cbrunet** [comment]
Ok, I see. Thank you the the bug report!
