### ISSUE TITLE
PHP error: Unsupported operand types 

### ISSUE THREAD

**Issue by ramos67** [cbrunet/typo3-cb_newscal#7]
Hi , 
installed version 1.1.1 from Ter , and from this git. Same result.
Loaded ext, inserted template setup.
Inserted news plugin in page and when switch mode to Calendar this error appear:

PHP Fatal error:  Unsupported operand types in /mysitepath/mysite/typo3conf/ext/cb_newscal/C
lasses/Hooks/T3libBefunc.php on line 71

thanks for your work!

**Comment by cbrunet** [comment]
I'm really confused. I cannot figure out what is causing this. Could you give me versions of PHP, TYPO3, and news extension you are using? Do you have any other loaded extensions that interact with the news extension? Did you tried to clear the caches from the install tool? When the view is not 'calendar' ('list' or 'details', for instance), is there a 'Template' tab under the 'Plugin' tab? Is there anything in it?

**Comment by ramos67** [comment]
Hi!
Php 5.4.29
TYPO3 6.2.9
TX_News 3.0.1
No , there's no ext that interacts with news (I think..)
I cleared the cache from install tool and manually removing the typo3temp dir
Yes is there Template tab and every fields is empty. There's also with calendar view and fields are always empty.
I hope this help, thanks!

**Comment by cbrunet** [comment]
If you replace lines 70-71 of  /mysitepath/mysite/typo3conf/ext/cb_newscal/C
lasses/Hooks/T3libBefunc.php by

```
$params['dataStructure']['sheets']['template']['ROOT']['el'] = array_merge(array('settings.monthsBefore' => $monthsBefore, 'settings.monthsAfter' => $monthsAfter),
                                                                                   $params['dataStructure']['sheets']['template']['ROOT']['el']);
```

do you get the same error?

**Comment by ramos67** [comment]
Hi! sorry for delay.

Changing with your code there's NO error. seems works fine.

Thanks!
