### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by alat54** [cbrunet/typo3-cb_newscal#8]
Hi, 

When i load the extension i have this error : 
Oops, an error occurred!
The template files "/xxx/htdocs/typo3conf/ext/cb_newscal/Resources/Private/Layouts/General.html", "/xxx/htdocs/typo3conf/ext/cb_newscal/Resources/Private/Layouts/General" could not be loaded.

Because there are no layouts files in directories...

Forget in archive? misconfiguration for me?

I'm on last versions for typo3 and cb_newscal (1.1.1)

Thanks

**Comment by cbrunet** [comment]
There is no layout included in cb_newscal because the General.html layout from news extension should be used. Did you change anything in TypoScript setup? plugin.tx_news.view.layoutRootPaths should e an array, and at least on item in it should be the default news layout path array, usualy [100] = EXT:news/Resources/Private/Layouts/ This is where the General.html layout is located.

**Comment by alat54** [comment]
Oh ! yeah i have modified the typoscript for personal templates for tx_news... but they are on 0 and 1
tx_news.templateLayouts {
        0 = layout 1
        1 = layout 2
}

this is the problem?

**Comment by cbrunet** [comment]
Is plugin.tx_news.view.layoutRootPath (without 's') set anywhere? If so, it would disable the fallback. Otherwise, extbase should search in all defined paths, starting from the lower indexes.

**Comment by alat54** [comment]
I have defined these path and i deactivate my template after the error... but it does the same :(

**Comment by cbrunet** [comment]
It is difficult to find the problem with so little information... Try using the TypoScript Object Browser and the Template Analyser to figure out what is the problem. Do not forget to clear General cache after modifying TypoScript setup. 

As a workaround, you could try to copy the General.html layout from news extension in one of your defined layout path.

**Comment by alat54** [comment]
Hi, 

Import of a "new" news static template and cb_news solves the problem. I don't know what's happened.
But i have a new bug now, when i want to show previous or next month or detail of news, i have this error "Reason: Segment "my_page_for_single_view"" was not a keyword for a postVarSet as expected on page with id=9."

The url is generated with a wrong format : http://www.xxxx.com/page_with_calendar/my_page_for_single_view/my_forlder_for_news/news1-copie-1/?tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Baction%5D=detail&cHash=c1fbfbe5b152a462c0a02e6da34f5a2e

I have real_url... is there any specific configuration?

thnaks a lot for help

**Comment by alat54** [comment]
Hum after an another import of all templates it's working... it's really strange...

**Comment by cbrunet** [comment]
Probably a cache issue. Sometime, it is very tricky. Since everything seems ok now, I close the issue.

**Comment by alat54** [comment]
thank for the help ;)
