### ISSUE TITLE
Error when trying to edit the flexform

### ISSUE THREAD

**Issue by kaolol** [cbrunet/typo3-cb_newscal#9]
Hi Charles,

I have installed your ext on TYPO3 6.2.
Look's cool !
Unfortunately when I try to edit the flexform in BE I have this error 
#1: PHP Warning: array_merge(): Argument #2 is not an array in /var/www/3cm/SpecialityDistribution/typo3conf/ext/cb_newscal/Classes/Hooks/T3libBefunc.php line 83 (More information)

Any idea on how to fix this ?
Thank you for sharing,
All the best,
Laurent

**Comment by cbrunet** [comment]
This is strange. Is there anything in your environment that could modify the Flexform? (user restrictions? other extension modifying news extension?) The second argument to array_merge() should be the already existing flexform of the Template tab. 

You could try to add

<pre>
if (!is_array($params['dataStructure']['sheets']['template']['ROOT']['el']) {
    $params['dataStructure']['sheets']['template']['ROOT']['el'] = array();
}
</pre>

at line 82, just before the array_merge function.
